//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/game_proto.proto
namespace game_proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
  public partial class Person : global::ProtoBuf.IExtensible
  {
    public Person() {}
    
    private string _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private string _pass;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pass
    {
      get { return _pass; }
      set { _pass = value; }
    }
    private int _log_time = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"log_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int log_time
    {
      get { return _log_time; }
      set { _log_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}